### ISSUE TITLE
NaN at GetResources() displayed in UI for some reason

### ISSUE THREAD

**Issue by Whitecat106** [Whitecat106/OrbitalDecay#56]

**Comment by zajc3w** [comment]
happened once when whole thing crashed over corrupted vesseldata.cfg file.
i bet persistent.sfs has fuelLost = NaN, check for me pls
will sort out solution for that tomorrow

**Comment by Whitecat106** [comment]
Thanks dude, 
The persistence does have fuelLost = NaN, might be related to the StationKeeping button issue too, ill see if I can get rid of it by deleting the module in the .sfs and restart, might just be from the efficiency update and the changes to the module code.

**Comment by zajc3w** [comment]
just change NaNs to 0 and reload save 
it may be a silly question but:
Is there a way to refresh my fork to your code after merge and further changes?

**Comment by Whitecat106** [comment]
Just reloaded and it works again, the Station Keeping issue must be a separate problem I'll have a look in a moment, I will add some 'if ... = double.NaN or float.NaN ... = 0' checks to make sure nothing gets set to a NaN.

**Comment by zajc3w** [comment]
i would use in RemoveResources:
double d
 if (double.TryParse(string, out d))
{
update fuelLost
}
else fuelLost = 0

**Comment by zajc3w** [comment]
Nan can appear in lost fuel only when ISP is 0 
Efficiency = 1/ISP; 
This should never happen, with ISP =0 station keeping and fuel removal is not possible.
 Station keeping status checks should be done before fuel manager gets called.sequencing needs double check here and adding safeguards as well
