### ISSUE TITLE
engine names unreadable

### ISSUE THREAD

**Issue by zajc3w** [Whitecat106/OrbitalDecay#57]
since 1.1 Part.partName does return "Part" or same unreadable name as Part.name
This needs to be sorted out to get right clik menu showing etidor style nice engine names.
ie LV-T30 "reliant" instead of current liquidEngine.

**Comment by Whitecat106** [comment]
I noticed this earlier, I think I had the same issue previously, ill see what I can find in the community API.

**Comment by Whitecat106** [comment]
Fixed using module.part.protoPartSnapshot.partInfo.title
