### ISSUE TITLE
TimeWarp.SetRate - Method not found - KSP 1.1.3

### ISSUE THREAD

**Issue by rmroc451** [Whitecat106/OrbitalDecay#73]
Just thought i would drop a line and say that I tried Orbital Decay (at my own risk) on my updated 1.1.3 KSP install. I know the mod isn't supported on 1.1.3 yet, but I figured this would be a good way to track this.

Looks like a similar issue that TriggerAU's Kerbal Alarm Clock had.

[EXC 10:20:04.939] MissingMethodException: Method not found: 'TimeWarp.SetRate'.
    WhitecatIndustries.DecayManager.RealisticDecaySimulator (.Vessel vessel)
    WhitecatIndustries.DecayManager.FixedUpdate ()

**Comment by Whitecat106** [comment]
Thanks for this one! Added to the 1.6.0 milestone, still running 1.1.2 here, will update to 1.1.3 after everything else for 1.6.0 is finished to correct this; shouldnt cause too many problems! :)

**Comment by rmroc451** [comment]
I was going to pull it down and try to fix it, sounds like a recompile
fixes it.

Had to run out for a bit though :)

On Sat, Jun 25, 2016, 3:41 PM Whitecat106 notifications@github.com wrote:

> Thanks for this one! Added to the 1.6.0 milestone, still running 1.1.2
> here, will update to 1.1.3 after everything else for 1.6.0 is finished to
> correct this; shouldnt cause too many problems! :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Whitecat106/OrbitalDecay/issues/73#issuecomment-228569585,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOX24ViOzQUfwmeCBSSGBAG7rtVJqbSLks5qPZKRgaJpZM4I-Xe_
> .
> 
> ## 

-Ryan Mroczenski

**Comment by Whitecat106** [comment]
Yes the issue appears fixed with my 1.1.3 compile! Should be free of this error in the 1.6.0 version soon! Thanks for letting me know! :)
